#!/bin/bash

rootDir=$(cd "$(dirname "$0")/.."; pwd)
. $rootDir/utility.sh

#clear trash that was generated by current user
#

WARNING_SIZE='2G'
WARNING_OVER='1'

function monitor (){
    TOTAL_SIZE=`du -sh ~/.Trash | awk '{print $1}'`

    #if the unit is equal
    if [ ${TOTAL_SIZE:0-1:1} = ${WARNING_SIZE:0-1:1} ]; then

        STR_LEN=${#TOTAL_SIZE}
        TOTAL_SIZE_NUM=${TOTAL_SIZE:0:STR_LEN-1}
        STR_LEN=${#WARNING_SIZE}
        WARNING_SIZE_NUM=${WARNING_SIZE:0:STR_LEN-1}
        
        TRASH_FLAG=$(echo "$TOTAL_SIZE_NUM >= $WARNING_SIZE_NUM " | bc)

        if [ $TRASH_FLAG = $WARNING_OVER ]; then
            speak "the trash total size over warning size. Clearing!!!"
            rm -rf ~/.Trash/*
        fi

    fi
}

function monitor_deamon (){
    while [ true ]; do
        
        monitor

        sleep 300               #5 minutes

    done
}



if [ $# -eq 0 ]; then
    speak "trash checking!"
    monitor
    exit 0
fi

while getopts ":d" optname
do
    case "$optname" in
    "d")
        echo "monitor_deamon"
        monitor_deamon
    ;;
    *)
        echo "others"
    ;;
    esac
done